name: VE Linux check

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  ve-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare QUICKCHECK_LOGS dir
        run: |
          mkdir -p QUICKCHECK_LOGS
          echo "QUICKCHECK_LOGS=$PWD/QUICKCHECK_LOGS" >> $GITHUB_ENV

      - name: Run VE Linux audit
        run: |
          chmod +x ./ve_parse.sh ./ve_kernel.sh
          ./ve_parse.sh audit
